import { c as create_ssr_component, a as subscribe, e as escape } from "../../../../chunks/ssr.js";
import "../../../../chunks/firebase.js";
import { t } from "../../../../chunks/i18n.js";
const css = {
  code: ".loader.svelte-sg8bjj{animation:svelte-sg8bjj-spin 1s linear infinite;border:4px solid rgba(0,0,0,.1);border-radius:50%;border-top-color:#3498db;height:40px;margin:0 auto;width:40px}@keyframes svelte-sg8bjj-spin{0%{transform:rotate(0deg)}to{transform:rotate(1turn)}}",
  map: `{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script>\\r\\n    import { onMount } from 'svelte';\\r\\n    import { fetchProducts } from '$lib/actions/firebase.js';\\r\\n    import {t} from '$lib/i18n';\\r\\n    let products = [];\\r\\n    let isLoading = true;\\r\\n\\r\\n    // Fetch products from Firebase on component mount\\r\\n    onMount(() => {\\r\\n        fetchProducts((fetchedProducts) => {\\r\\n            products = fetchedProducts;\\r\\n            isLoading = false; // Stop loading when data is fetched\\r\\n            console.log('Fetched products:', products);\\r\\n        });\\r\\n    });\\r\\n<\/script>\\r\\n\\r\\n<div class=\\"container mx-auto py-10\\">\\r\\n    <h1 class=\\"text-3xl font-bold text-center mb-5 text-white\\">{$t(\\"itl\\")}</h1>\\r\\n\\r\\n    {#if isLoading}\\r\\n        <div class=\\"text-center py-20\\">\\r\\n            <div class=\\"loader\\">Loading...</div>\\r\\n        </div>\\r\\n    {:else}\\r\\n        <div class=\\"grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6\\">\\r\\n            {#if products.length}\\r\\n                {#each products as product}\\r\\n                    <div class=\\"bg-white shadow-md rounded-lg overflow-hidden\\">\\r\\n                        <img src={product.imageUrl || 'placeholder-image-url.jpg'} alt={product.name} class=\\"w-full h-40 object-cover\\">\\r\\n                        <div class=\\"p-4\\">\\r\\n                            <h2 class=\\"text-lg font-semibold\\">{product.name}</h2>\\r\\n                            <p class=\\"text-gray-500\\">Price: ₹{product.price}</p>\\r\\n                            <p class=\\"text-gray-500\\">{product.kg} Kg</p>\\r\\n                            <p class=\\"text-gray-400 text-sm\\">ID: {product.id}</p>\\r\\n                            <p class=\\"text-gray-400 text-sm\\">Date: {product.date}</p>\\r\\n                        </div>\\r\\n                    </div>\\r\\n                {/each}\\r\\n            {:else}\\r\\n                <p class=\\"text-center text-gray-500\\">No products available.</p>\\r\\n            {/if}\\r\\n        </div>\\r\\n    {/if}\\r\\n</div>\\r\\n\\r\\n<style>.loader{animation:spin 1s linear infinite;border:4px solid rgba(0,0,0,.1);border-radius:50%;border-top-color:#3498db;height:40px;margin:0 auto;width:40px}@keyframes spin{0%{transform:rotate(0deg)}to{transform:rotate(1turn)}}</style>\\r\\n"],"names":[],"mappings":"AA8CO,qBAAO,CAAC,UAAU,kBAAI,CAAC,EAAE,CAAC,MAAM,CAAC,QAAQ,CAAC,OAAO,GAAG,CAAC,KAAK,CAAC,KAAK,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,EAAE,CAAC,CAAC,cAAc,GAAG,CAAC,iBAAiB,OAAO,CAAC,OAAO,IAAI,CAAC,OAAO,CAAC,CAAC,IAAI,CAAC,MAAM,IAAI,CAAC,WAAW,kBAAI,CAAC,EAAE,CAAC,UAAU,OAAO,IAAI,CAAC,CAAC,EAAE,CAAC,UAAU,OAAO,KAAK,CAAC,CAAC"}`
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let $t, $$unsubscribe_t;
  $$unsubscribe_t = subscribe(t, (value) => $t = value);
  $$result.css.add(css);
  $$unsubscribe_t();
  return `<div class="container mx-auto py-10"><h1 class="text-3xl font-bold text-center mb-5 text-white">${escape($t("itl"))}</h1> ${`<div class="text-center py-20" data-svelte-h="svelte-aoxmif"><div class="loader svelte-sg8bjj">Loading...</div></div>`} </div>`;
});
export {
  Page as default
};
